### ISSUE TITLE
Does not link

### ISSUE THREAD

**Issue by gregkerzhner** [smartlook/smartlook-react-native-sdk#14]
Following the installation instructions, the app fails on the linking stage.  
<img width="1429" alt="Screen Shot 2019-09-17 at 2 00 47 PM" src="https://user-images.githubusercontent.com/2031812/65079261-96fa2680-d953-11e9-9b4c-309563d401bf.png">

**Comment by pavel-kroh-smartlook** [comment]
Hi, this means that `Smartlook.framework` is not properly present in your iOS project target. It could be e.g., caching issue too (RN is quite prone to it). Make sure `Smartlook.framework` is indeed **copied** to the Xcode project and part of the target you build (perhaps this happens when you build for unit tests?).

**Comment by pavel-kroh-smartlook** [comment]
We are also amending our documentation with respect to the project targets. Please let us know if my assumption that the cause of the issue is that `Smartlook.framework` is not part of some relevant build target is correct.

**Comment by pavel-kroh-smartlook** [comment]
New version of React Native was released today with updated linking (Cocoapods support.) that perhaps solve this issue. For details refer here: https://smartlook.github.io/docs/sdk/react-native/
