### ISSUE TITLE
error compiling ios - tractNavigationEventWithControllerId  error

### ISSUE THREAD

**Issue by elirangoshen** [smartlook/smartlook-react-native-sdk#15]
Hi, i'm getting an error of "no known class method for selector  tractNavigationEventWithControllerId" when trying to compile ios. 

macOS
node: v11.14.0
react-native: 0.60.4
smartlook-react-native-wrapper: 0.13.0

**Comment by pavel-kroh-smartlook** [comment]
Hi, this happens when there is an older version of `Smartlook.framework` linked in the app. Please uninstall Smartlook plugin, check iOS Xcode project if there is any version Smartlook.framework in it and delete it, clean all caches and preferably also kill watchman and then install Smartlook again.

**Comment by pavel-kroh-smartlook** [comment]
Please update to the latest Smartlook module as described here: https://github.com/smartlook/smartlook-react-native-bridge
